"""added meber_key in Collaboration and table_args in VerificationCode

Revision ID: 3d17fea78ba8
Revises: 07e03f317403
Create Date: 2026-09-06 14:31:00.733460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d17fea78ba8'
down_revision: Union[str, Sequence[str], None] = '07e03f317403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'collaborations',
        sa.Column('member_key', sa.String(length=64), nullable=True),
    )
    op.execute(
        "UPDATE collaborations SET member_key = 'legacy_' || collaboration_id "
        "WHERE member_key IS NULL"
    )
    with op.batch_alter_table('collaborations') as batch_op:
        batch_op.alter_column('member_key', nullable=False)
        batch_op.create_index(
            'ix_collaborations_member_key', ['member_key'], unique=True
        )
    with op.batch_alter_table('verification_codes') as batch_op:
        batch_op.create_unique_constraint(
            'uq_verification_user_purpose', ['user_id', 'purpose']
        )
    # op.add_column('collaborations', sa.Column('member_key', sa.String(length=64), nullable=False))
    # op.create_index(op.f('ix_collaborations_member_key'), 'collaborations', ['member_key'], unique=True)
    # op.create_unique_constraint('uq_verification_user_purpose', 'verification_codes', ['user_id', 'purpose'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_codes') as batch_op:
        batch_op.drop_constraint('uq_verification_user_purpose', type_='unique')
    with op.batch_alter_table('collaborations') as batch_op:
        batch_op.drop_index('ix_collaborations_member_key')
        batch_op.drop_column('member_key')
    # op.drop_constraint('uq_verification_user_purpose', 'verification_codes', type_='unique')
    # op.drop_index(op.f('ix_collaborations_member_key'), table_name='collaborations')
    # op.drop_column('collaborations', 'member_key')
    # ### end Alembic commands ###
