"""initial tables

Revision ID: 40b295345c97
Revises: 
Create Date: 2026-08-21 19:20:00.385802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40b295345c97'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaborations',
    sa.Column('collaboration_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('collaboration_type', sa.String(length=255), nullable=True),
    sa.Column('collaboration_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('collaboration_id')
    )
    op.create_index(op.f('ix_collaborations_collaboration_type'), 'collaborations', ['collaboration_type'], unique=False)
    op.create_table('conferences',
    sa.Column('conference_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('conference_id')
    )
    op.create_index(op.f('ix_conferences_name'), 'conferences', ['name'], unique=False)
    op.create_table('institutions',
    sa.Column('institution_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=128), nullable=False),
    sa.Column('type', sa.Enum('UNIVERSITY', 'RESEARCH_INSTITUTE', 'GOVERNMENT_LAB', 'PRIVATE_COMPANY', 'NONPROFIT_ORGANIZATION', name='institutiontype'), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('institution_id')
    )
    op.create_index(op.f('ix_institutions_name'), 'institutions', ['name'], unique=True)
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='projectstatus'), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('revoked_tokens',
    sa.Column('token_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_index(op.f('ix_revoked_tokens_token'), 'revoked_tokens', ['token'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('RESEARCHER', 'INSTITUTION_ADMIN', 'REVIEWER', 'SYSTEM_ADMIN', name='userrole'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'REJECTED', 'BANNED', name='userstatus'), nullable=False),
    sa.Column('pending_email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_verified'), 'users', ['is_verified'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('publications',
    sa.Column('publication_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('publication_type', sa.Enum('JOURNAL', 'CONFERENCE', 'BOOK', 'PATENT', 'REPORT', name='publicationtype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'PUBLISHED', 'ARCHIVED', name='publicationstatus'), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('conference_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.conference_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('publication_id')
    )
    op.create_index(op.f('ix_publications_conference_id'), 'publications', ['conference_id'], unique=False)
    op.create_index(op.f('ix_publications_doi'), 'publications', ['doi'], unique=True)
    op.create_index(op.f('ix_publications_status'), 'publications', ['status'], unique=False)
    op.create_table('researchers',
    sa.Column('researcher_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('orcid', sa.String(length=16), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('research_interests', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.institution_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('researcher_id'),
    sa.UniqueConstraint('orcid'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_researchers_institution_id'), 'researchers', ['institution_id'], unique=False)
    op.create_table('verification_codes',
    sa.Column('code_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('secret', sa.String(length=256), nullable=False),
    sa.Column('code', sa.String(length=256), nullable=False),
    sa.Column('purpose', sa.Enum('REGISTER', 'LOGIN', 'CHANGE_EMAIL', name='verificationpurpose'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('code_id')
    )
    op.create_index(op.f('ix_verification_codes_purpose'), 'verification_codes', ['purpose'], unique=False)
    op.create_index(op.f('ix_verification_codes_user_id'), 'verification_codes', ['user_id'], unique=False)
    op.create_table('citations',
    sa.Column('citation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('citing_publication_id', sa.Integer(), nullable=False),
    sa.Column('cited_publication_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cited_publication_id'], ['publications.publication_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['citing_publication_id'], ['publications.publication_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('citation_id'),
    sa.UniqueConstraint('citing_publication_id', 'cited_publication_id', name='uq_publication_citation')
    )
    op.create_table('collaboration_researchers',
    sa.Column('collaboration_id', sa.Integer(), nullable=False),
    sa.Column('researcher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collaboration_id'], ['collaborations.collaboration_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['researcher_id'], ['researchers.researcher_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collaboration_id', 'researcher_id')
    )
    op.create_index(op.f('ix_collaboration_researchers_researcher_id'), 'collaboration_researchers', ['researcher_id'], unique=False)
    op.create_table('project_researchers',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('researcher_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('PI', 'CO_PI', 'MEMBER', name='projectrole'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['researcher_id'], ['researchers.researcher_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'researcher_id')
    )
    op.create_table('publication_authors',
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('researcher_id', sa.Integer(), nullable=False),
    sa.Column('author_order', sa.Integer(), nullable=False),
    sa.Column('is_corresponding', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.publication_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['researcher_id'], ['researchers.researcher_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('publication_id', 'researcher_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publication_authors')
    op.drop_table('project_researchers')
    op.drop_index(op.f('ix_collaboration_researchers_researcher_id'), table_name='collaboration_researchers')
    op.drop_table('collaboration_researchers')
    op.drop_table('citations')
    op.drop_index(op.f('ix_verification_codes_user_id'), table_name='verification_codes')
    op.drop_index(op.f('ix_verification_codes_purpose'), table_name='verification_codes')
    op.drop_table('verification_codes')
    op.drop_index(op.f('ix_researchers_institution_id'), table_name='researchers')
    op.drop_table('researchers')
    op.drop_index(op.f('ix_publications_status'), table_name='publications')
    op.drop_index(op.f('ix_publications_doi'), table_name='publications')
    op.drop_index(op.f('ix_publications_conference_id'), table_name='publications')
    op.drop_table('publications')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_verified'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_revoked_tokens_token'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_institutions_name'), table_name='institutions')
    op.drop_table('institutions')
    op.drop_index(op.f('ix_conferences_name'), table_name='conferences')
    op.drop_table('conferences')
    op.drop_index(op.f('ix_collaborations_collaboration_type'), table_name='collaborations')
    op.drop_table('collaborations')
    # ### end Alembic commands ###
