"""removed column 'code' from verification_codes

Revision ID: 5a0aff7c71f5
Revises: 40b295345c97
Create Date: 2026-08-21 20:48:38.251096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a0aff7c71f5'
down_revision: Union[str, Sequence[str], None] = '40b295345c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification_codes', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_codes', sa.Column('code', sa.VARCHAR(length=256), nullable=False))
    # ### end Alembic commands ###
