"""initial tables

Revision ID: 70b413fc444e
Revises: 
Create Date: 2026-08-06 20:49:16.892106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70b413fc444e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conferences',
    sa.Column('conference_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('conference_id')
    )
    op.create_table('institutions',
    sa.Column('institution_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('institution_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('revoked_tokens',
    sa.Column('token_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('publications',
    sa.Column('publication_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('conference_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.conference_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('publication_id'),
    sa.UniqueConstraint('doi')
    )
    op.create_table('researchers',
    sa.Column('researcher_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('orcid', sa.String(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('research_interests', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.institution_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('researcher_id'),
    sa.UniqueConstraint('orcid'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('citations',
    sa.Column('citation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('citing_publication_id', sa.Integer(), nullable=False),
    sa.Column('cited_publication_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cited_publication_id'], ['publications.publication_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['citing_publication_id'], ['publications.publication_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('citation_id'),
    sa.UniqueConstraint('citing_publication_id', 'cited_publication_id', name='uq_publication_citation')
    )
    op.create_table('collaborations',
    sa.Column('collaboration_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('researcher_id_1', sa.Integer(), nullable=False),
    sa.Column('researcher_id_2', sa.Integer(), nullable=False),
    sa.Column('collaboration_type', sa.String(length=100), nullable=True),
    sa.Column('collaboration_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['researcher_id_1'], ['researchers.researcher_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['researcher_id_2'], ['researchers.researcher_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collaboration_id'),
    sa.UniqueConstraint('researcher_id_1', 'researcher_id_2', name='uq_researcher_collaboration')
    )
    op.create_table('project_researchers',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('researcher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['researcher_id'], ['researchers.researcher_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'researcher_id')
    )
    op.create_table('publication_authors',
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('researcher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.publication_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['researcher_id'], ['researchers.researcher_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('publication_id', 'researcher_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publication_authors')
    op.drop_table('project_researchers')
    op.drop_table('collaborations')
    op.drop_table('citations')
    op.drop_table('researchers')
    op.drop_table('publications')
    op.drop_table('users')
    op.drop_table('revoked_tokens')
    op.drop_table('projects')
    op.drop_table('institutions')
    op.drop_table('conferences')
    # ### end Alembic commands ###
