"""added column external_authors in publications

Revision ID: 9da663cc1086
Revises: 691ed2fa653e
Create Date: 2026-08-23 22:35:43.726665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9da663cc1086'
down_revision: Union[str, Sequence[str], None] = '691ed2fa653e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_project_researchers_researcher_id'), 'project_researchers', ['researcher_id'], unique=False)
    op.create_index(op.f('ix_publication_authors_researcher_id'), 'publication_authors', ['researcher_id'], unique=False)
    op.add_column('publications', sa.Column('external_authors', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'external_authors')
    op.drop_index(op.f('ix_publication_authors_researcher_id'), table_name='publication_authors')
    op.drop_index(op.f('ix_project_researchers_researcher_id'), table_name='project_researchers')
    # ### end Alembic commands ###
