"""update models 2

Revision ID: c60d6a0d9aa3
Revises: ba8d7a450496
Create Date: 2026-08-16 15:33:41.200996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c60d6a0d9aa3'
down_revision: Union[str, Sequence[str], None] = 'ba8d7a450496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_collaboration_researchers_researcher_id'), 'collaboration_researchers', ['researcher_id'], unique=False)
    op.alter_column('conferences', 'location',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('institutions', 'city',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('institutions', 'country',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.add_column('researchers', sa.Column('name', sa.String(length=128), nullable=False))
    op.drop_column('researchers', 'full_name')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.add_column('researchers', sa.Column('full_name', sa.VARCHAR(), nullable=False))
    op.drop_column('researchers', 'name')
    op.alter_column('institutions', 'country',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('institutions', 'city',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('conferences', 'location',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_collaboration_researchers_researcher_id'), table_name='collaboration_researchers')
    # ### end Alembic commands ###
