from abc import ABC, abstractmethod


class EmailNotifier(ABC):
    @abstractmethod
    def send_approval_notification(self, email: str) -> None: ...
    @abstractmethod
    def send_rejection_notification(self, email: str) -> None: ...
    @abstractmethod
    def send_ban_notification(self, email: str) -> None: ...
    @abstractmethod
    def send_verification_email(self, email: str, code: str) -> None: ...
